### ISSUE TITLE
你好，在使用功能jumpserver同步的时候报错

### ISSUE THREAD

**Issue by jimmi-lee** [starsliao/ConsulManager#67]
点击同步后提示"【huaweicloud/devops】同步功能开启失败，请查看后端日志",日志信息如下：

 17:54:19 | INFO | 【JOB】===>huaweicloud,devops,JMS同步开始
17:54:20 | ERROR |   【JMS】身份认证信息未提供。
http://192.168.30.228/api/v1/assets/nodes/13e5e946-1534-4a9d-8ec0-2a451101706b/children/==>{'Content-Type': 'application/json', 'Authorization': 'Token 765351487fb3eb83972e343cba49c226888a1775'}
17:54:20 | ERROR | string indices must be integers
Traceback (most recent call last):
  File "/flask/views/jms.py", line 144, in post
    runjob(jms_job_id)
  File "/flask/views/jobs.py", line 33, in runjob
    Scheduler.run_job(jobid)
  File "/usr/local/lib/python3.10/site-packages/flask_apscheduler/scheduler.py", line 284, in run_job
    job.func(*job.args, **job.kwargs)
  File "/flask/units/jms/sync_jms.py", line 135, in run
    new_node_dict = create_node(jms_url,headers,now,node_id,cloud,account)
  File "/flask/units/jms/sync_jms.py", line 18, in create_node
    if v not in [i['value'] for i in jms_node_list]:
  File "/flask/units/jms/sync_jms.py", line 18, in <listcomp>
    if v not in [i['value'] for i in jms_node_list]:
TypeError: string indices must be integers

【huaweicloud/devops】同步功能开启失败！
172.18.0.3 - - [18/Apr/2023 17:54:20] "POST /api/jms/sync HTTP/1.0" 200 -

麻烦看下什么的地方每有配置对。

**Comment by dbdocker** [comment]
可以 贴一下 示例图吗。我看一下

**Comment by starsliao** [comment]
jumpserverV3版本 请更新consulmanager后重试
